api_version = "2026-04"
uid = "28d50eab-f21c-e392-6a3b-a505aa367dbf34da9978"

[[extensions]]
name = "t:name"
handle = "validation-function"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
