# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd9587ee1d617019e802f1cc14d5ff3e"
name = "require-billing-phone-number"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
